//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public int emailid { get; set; }
        public int personidfk { get; set; }
        public int typeeidfk { get; set; }
        public string email1 { get; set; }
    
        public virtual person person { get; set; }
        public virtual typeemail typeemail { get; set; }
    }
}
