//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZapKnEntities : DbContext
    {
        public ZapKnEntities()
            : base("name=ZapKnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<email> email { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<phone> phone { get; set; }
        public virtual DbSet<photo> photo { get; set; }
        public virtual DbSet<typeemail> typeemail { get; set; }
        public virtual DbSet<typephone> typephone { get; set; }
    }
}
