//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        public int phoneid { get; set; }
        public int personidfk { get; set; }
        public int typepidfk { get; set; }
        public string phonenumber { get; set; }
    
        public virtual person person { get; set; }
        public virtual typephone typephone { get; set; }
    }
}
